{
  "submission_id": "S16",
  "user_id": "U1",
  "problem_id": "P1",
  "timestamp": "2025-08-26T11:25:36Z",
  "status": "runtime_error",
  "language": "c",
  "test_results": [
    {
      "test_case_number": 1,
      "status": "runtime_error",
      "message": "Runtime Error: Docker error: error during connect: Get \"http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.49/info\": open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.\n",
      "execution_time": 0,
      "memory_usage": 0,
      "actual_output": "",
      "expected_output": "2"
    },
    {
      "test_case_number": 2,
      "status": "runtime_error",
      "message": "Runtime Error: Docker error: error during connect: Get \"http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.49/info\": open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.\n",
      "execution_time": 0,
      "memory_usage": 0,
      "actual_output": "",
      "expected_output": "4"
    }
  ]
}